version: '3.9'

name: pdanetwork

services:
  db:
    image: postgres:16
    container_name: pdanetwork_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=pdanet
      - POSTGRES_PASSWORD=pdanet
    ports:
      - "5432:5432"