spring:
    config:
        import: startup.yml
    datasource:
        hikari:
            auto-commit: false
        password: 'pass'
        url: jdbc:postgresql://localhost:5432/pdanet
        username: pdanet
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                enable_lazy_load_no_trans: false
                format_sql: true
        show-sql: false
    mail:
        host: mail.artux.net
        password: pass
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
        protocol: smtp
        username: noreply@artux.net
    mvc:
        hiddenmethod:
            filter:
                enabled: true

admin:
    address: https://admin.artux.net/
cdn:
    address: https://cdn.artux.net/
logging:
    file:
        name: logs/logfile.log
management:
    endpoints:
        web:
            exposure:
                include: '*'
postman:
    invite:
        link: https://app.getpostman.com/join-team?invite_code=7314a144fdf6276193f426844376200b
    team:
        link: https://pdanet.postman.co/workspaces
quest:
    stories:
        init:
            enabled: true
registration:
    confirmation:
        enabled: true
server:
    error:
        include-binding-errors: on_param
        include-exception: true
        include-message: always
    host: localhost:8080
    protocol: http
    servlet:
        contextPath: /pdanetwork
    websocket:
        protocol: ws

springdoc:
    api-docs:
        enabled: true
    show-actuator: false
    swagger-ui:
        enabled: true
stories:
    directory: /srv/pda
    github:
        address: https://api.github.com/repos/artux-net/pda-quests/zipball
        token: pass

jwt:
    private:
        key: classpath:app.key
    public:
        key: classpath:app.pub