version: '3.9'

name: pdanetwork

services:
  db:
    image: postgres
    container_name: pdanetwork_db
    restart: unless-stopped

    environment:
      - POSTGRES_USER=pdanetwork
      - POSTGRES_PASSWORD=pass
    ports:
      - "9999:5432"

  backend:
    build:
      context: ..

    container_name: pdanetwork_back
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SERVER_PROTOCOL=http
      - SERVER_HOST=localhost:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pdanetwork
      - SPRING_DATASOURCE_USERNAME=pdanetwork
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
