version: '3'

services:
  db:
    image: postgres
    container_name: pdanetwork_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=pdanetwork
      - POSTGRES_PASSWORD=pass
    ports:
      - "9999:5432"

  backend:
    image: registry.artux.net/pdanet/pdanetwork:${IMAGE_TAG}
    container_name: pdanetwork_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SERVER_HOST=dev.artux.net
      - SERVER_PROTOCOL=https
      - SERVER_WEBSOCKET_PROTOCOL=wss
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pdanetwork
      - SPRING_DATASOURCE_USERNAME=pdanetwork
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8888:8080"
