version: '3.9'

name: pdanetwork

services:
  db:
    image: postgres:15
    container_name: pdanetwork_db
    restart: unless-stopped
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pdanetwork
      - POSTGRES_PASSWORD=pass
    ports:
      - "9999:5432"
    labels:
      io.portainer.accesscontrol.teams: dev,prod

  backend:
    image: registry.artux.net/pdanetwork:${IMAGE_TAG}
    container_name: pdanetwork_backend
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SERVER_HOST=dev.artux.net
      - SERVER_PROTOCOL=https
      - SERVER_WEBSOCKET_PROTOCOL=wss
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pdanetwork
      - SPRING_DATASOURCE_USERNAME=pdanetwork
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8002:8080"
    labels:
      io.portainer.accesscontrol.teams: dev,prod
  frontend:
    image: registry.artux.net/pda-admin-web:dev
    container_name: pdanet_admin_panel
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - BASE_PATH=/panel
      - API_URL=https://dev.artux.net/pdanetwork/:path*
    ports:
      - "8001:3000"
    labels:
      io.portainer.accesscontrol.teams: dev,prod
