name: ${STACK_NAME}

networks:
  pda-net:
    driver: overlay

x-dev: &dev-profile
  networks:
    - pda-net
  profiles:
    - dev
  labels:
    io.portainer.accesscontrol.teams: dev,prod

x-prod: &prod-profile
  networks:
    - pda-net
  profiles:
    - prod
  labels:
    io.portainer.accesscontrol.teams: prod

x-backend-template: &backend
  image: registry.artux.net/pdanetwork:${IMAGE_TAG}
  pull_policy: always
  restart: unless-stopped
  deploy:
    replicas: 2
    update_config:
      parallelism: 1
      delay: 10s
      failure_action: rollback
      monitor: 30s
      max_failure_ratio: 0.3
    restart_policy:
      condition: on-failure
    resources:
      limits:
        memory: 4G
      reservations:
        memory: 3G

x-frontend-template: &frontend
  image: registry.artux.net/pda-admin-web:${WEB_IMAGE_TAG}
  pull_policy: always
  restart: unless-stopped
  networks:
    - pda-net

services:
  backend-prod:
    <<:
      - *backend
      - *prod-profile
    environment:
      SPRING_PROFILES_ACTIVE: default, dev, prod
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PROTOCOL: https
      SERVER_WEBSOCKET_PROTOCOL: wss
      SPRING_DATASOURCE_URL: jdbc:postgresql://ip:port/${DATASOURCE_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      JAVA_TOOL_OPTIONS: >-
        -Xms512m 
        -Xmx2048m
        -XX:MaxGCPauseMillis=150
        -Xlog:gc*:file=/tmp/gc.log:time
        -XX:+HeapDumpOnOutOfMemoryError 
        -XX:HeapDumpPath=/tmp/heapdumps
        -XX:+ExitOnOutOfMemoryError
        -XX:+UseStringDeduplication
        -XX:+AlwaysActAsServerClassMachine
        -XX:+UseG1GC
        -Duser.timezone=Europe/Moscow
    ports:
      - "8080:8080"

  backend-dev:
    <<:
      - *backend
      - *dev-profile
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: default, dev
      SERVER_HOST: dev.artux.net
      SERVER_PROTOCOL: https
      SERVER_WEBSOCKET_PROTOCOL: wss
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pdanetwork
      SPRING_DATASOURCE_USERNAME: pdanetwork
      SPRING_DATASOURCE_PASSWORD: "pass"
    ports:
      - "8002:8080"
    networks:
       - pda-net
  db:
    <<: *dev-profile
    image: postgres:15
    container_name: pdanetwork_db
    restart: unless-stopped
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pdanetwork
      - POSTGRES_PASSWORD=pass
    ports:
      - "9999:5432"

  frontend-dev:
    <<:
      - *frontend
      - *dev-profile
    depends_on:
      - backend-dev
    environment:
      - BASE_PATH=panel
      - API_URL=https://dev.artux.net/pdanetwork
    ports:
      - "8001:3000"

  frontend-prod:
    <<:
      - *frontend
      - *prod-profile
    depends_on:
      - backend-prod
    environment:
      - BASE_PATH=panel
      - API_URL=https://app.artux.net/pdanetwork
    ports:
      - "9001:3000"

  autoheal: # restarts unhealthy containers
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pda-net