server:
    host: localhost:8080
    protocol: http
    servlet:
        contextPath: /pdanetwork
    websocket:
        protocol: ws
    error:
        include-binding-errors: on_param
        include-exception: true
        include-message: always

spring:
    main:
        banner-mode: off
    profiles:
        active: default, dev
    jpa:
        hibernate:
            ddl-auto: none
        open-in-view: false
        properties:
            hibernate:
                enable_lazy_load_no_trans: false
                format_sql: true
        show-sql: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    mvc:
        hiddenmethod:
            filter:
                enabled: true

management:
    prometheus:
        metrics:
            export:
                enabled=true
    endpoints:
        web:
            exposure:
                include: '*'

quest:
    stories:
        init:
            enabled: true