name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        path: target/*.jar
    - run: |
        ls
    
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - run: |
        ls
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
         context: .
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/pdanetwork:latest
