name: Backup database

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_call:
  workflow_dispatch:

jobs:
  dump:
    runs-on: self-hosted
    name: 'Dump Backup'
    steps:
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    - name: Postgres Dump Backup
      uses: tj-actions/pg-dump@v3
      with:
        database_url: ${{secrets.PDA_DATABASE_URL}}
        postgresql_version: 14
        path: "backups/backup.sql"
        options: "-O"
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      env: 
        NOW: $NOW
      with:
        name: "$NOW"
        path: backups/backup.sql

