name: ⚙️Backup database

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_call:
  workflow_dispatch:

jobs:
  dump:
    runs-on: self-hosted
    name: 'Dump Backup'
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - name: Postgres Dump Backup
        run: |
          pg_dump -U pdanet -f backup.sql --no-owner --no-privileges

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date }}
          path: backup.sql

