name: 🚀️Deploy to server (auto-detect profile)

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    name: Deploy on server (auto-detecting profile based on ref)
    uses: ./.github/workflows/deploy.yml
    secrets: inherit