name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "dev"]

jobs:
  test:
   uses: ./.github/workflows/test.yml
  build:
    needs: test
    runs-on: self-hosted
    name: 'Build and upload artifact'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        path: target/*.jar

    - name: Login to Artux registry
      uses: docker/login-action@v2
      with:
        registry: registry.artux.net
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        logout: false

    - name: Build and push docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: registry.artux.net/pdanetwork:${{github.run_number}}

  deploy:
    needs: build
    name: 'Deploy image on server'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - env:
          IMAGE_TAG:
            ${{github.run_number}}
        run: |
          docker login registry.artux.net -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}}
          docker compose -f "./docker/compose.dev.yml" pull backend
          docker compose -f "./docker/compose.dev.yml" up
          docker system prune -a -f
        

