name: CI/CD Dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  test:
   uses: ./.github/workflows/test.yml
   
  build:
    needs: test
    runs-on: self-hosted
    name: 'Build and upload artifact'
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20'
        cache: 'gradle'
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.4

    - run: ./gradlew build --no-daemon -x test

    - name: Login to Artux registry
      uses: docker/login-action@v2
      with:
        registry: registry.artux.net
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        logout: false

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          registry.artux.net/pdanetwork
        tags: |
          type=ref,event=branch

    - name: Build and push docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}

  deploy:
    needs: build
    name: 'Deploy Compose on server'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Run services
        env:
          IMAGE_TAG: dev

        run: |
          docker login registry.artux.net -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}}
          
          docker compose -f "./docker/compose.dev.yml" pull
          docker compose -f "./docker/compose.dev.yml" down
          docker compose -f "./docker/compose.dev.yml" up -d 
          docker system prune -a -f
        

