name: Deploy profile

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: Profile to deploy
        default: dev
        options:
          - prod
          - dev

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  backup-db:
    name: Backup DB
    uses: ./.github/workflows/backup.yml

  build:
    name: Build and upload artifact
    needs: test
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs:
      - build
      - backup-db

    name: 'Deploy on server'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      tag: $GITHUB_REF
      profile: ${{ github.event.inputs.profile }}
