name: Run old master

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag of docker image

jobs:
  backupdb:
    uses: ./.github/workflows/backup.yml

  deploy:
    needs: 
     - backupdb
     
    name: 'Deploy Compose with tag on server'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Run services
        env:
          DATASOURCE_USERNAME: ${{secrets.DATASOURCE_USERNAME}}
          DATASOURCE_PASSWORD: ${{secrets.DATASOURCE_PASSWORD}}
          DATASOURCE_DB_NAME: ${{secrets.DATASOURCE_DB_NAME}}
          SERVER_HOST: app.artux.net
          IMAGE_TAG: ${{ github.event.inputs.tag }}

        run: |
          docker login registry.artux.net -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}}
          
          docker compose -f "./docker/compose.master.yml" pull
          docker compose -f "./docker/compose.master.yml" down
          docker compose -f "./docker/compose.master.yml" up -d 
          docker system prune -a -f
        

