name: Test

on:
  workflow_call:
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test artifact'
    steps:   
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20'
        cache: 'gradle'

    - name: Test with Gradle
      run: ./gradlew test

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Gradle Tests
        path: ./**/TEST-*.xml
        reporter: java-junit

