name: Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test artifact'
    steps:   
    - uses: actions/checkout@v3
    
    - name: Test with Gradle
      run: ./gradlew test
