name: Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test artifact'
    steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@< version >
    
    - uses: actions/checkout@v3
    
    - name: Test with Maven
      run: mvn clean test
