name: Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test artifact'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
        
    - name: Test with Maven
      run: mvn clean test
